version: '3.8'
services:
  front-flight:
    image: "ghcr.io/tup-utn-frc-lciii/flight-check-in-front-end"
    build: .
    ports:
      - "4200:4200"
    networks:
      - back-end-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: flights
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - front-flight
      - mysql
    networks:
      - back-end-network

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: sa
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - back-end-network
    restart: unless-stopped

networks:
  back-end-network:
    driver: bridge

volumes:
  mysql_data: